import 'workout_models.dart';
export 'workout_models.dart';

class WorkoutTemplateModels {
  static List<WorkoutDayPlan> getDefault7DayPlan() {
    return WorkoutPresetSplits.getDefaultWeeklyPlan();
  }

  static String getIllustrationForExercise(String name) {
    final clean = name.toLowerCase();
    if (clean.contains('bench') || clean.contains('chest') || clean.contains('push')) return '🏋️';
    if (clean.contains('squat') || clean.contains('leg') || clean.contains('calf')) return '🦵';
    if (clean.contains('pull') || clean.contains('row') || clean.contains('lat') || clean.contains('deadlift')) return '🧗';
    if (clean.contains('shoulder') || clean.contains('press') || clean.contains('delt')) return '💪';
    if (clean.contains('bicep') || clean.contains('curl')) return '💪';
    if (clean.contains('tricep') || clean.contains('dip')) return '⚡';
    if (clean.contains('core') || clean.contains('ab') || clean.contains('plank')) return '🧘';
    if (clean.contains('run') || clean.contains('cardio') || clean.contains('hiit')) return '🏃';
    return '🏋️';
  }
}

class WorkoutPresetSplits {
  static List<WorkoutDayPlan> getDefaultWeeklyPlan() {
    return [
      WorkoutDayPlan(
        id: 'plan_monday',
        dayName: 'Monday',
        workoutName: 'Chest & Triceps Hypertrophy',
        muscleGroup: 'Chest, Triceps & Front Delts',
        estimatedDurationMinutes: 50,
        difficulty: 'Intermediate',
        status: WorkoutStatus.planned,
        exercises: [
          ExerciseDetail(
            id: 'mon_ex_1',
            name: 'Barbell Bench Press',
            targetMuscle: 'Mid Chest & Pec Major',
            secondaryMuscles: 'Triceps, Anterior Delts',
            equipment: 'Barbell & Flat Bench',
            sets: 4,
            reps: 8,
            weightKg: 60.0,
            restSeconds: 90,
            instructions: 'Plant feet firmly on the ground. Retract scapula, lower bar with control to lower chest, then drive upwards explosively.',
            photoUrl: '🏋️',
            previousPerformance: '4 sets × 8 reps @ 60kg',
          ),
          ExerciseDetail(
            id: 'mon_ex_2',
            name: 'Incline Dumbbell Press',
            targetMuscle: 'Upper Clavicular Chest',
            secondaryMuscles: 'Front Deltoids',
            equipment: 'Dumbbells & Incline Bench (30°)',
            sets: 4,
            reps: 10,
            weightKg: 20.0,
            restSeconds: 75,
            instructions: 'Set bench at 30 degrees. Keep wrists stacked over elbows. Press upwards in an arc without clanking dumbbells at the top.',
            photoUrl: '🏋️',
            previousPerformance: '4 sets × 10 reps @ 20kg',
          ),
          ExerciseDetail(
            id: 'mon_ex_3',
            name: 'Cable Pec Flyes / Crossover',
            targetMuscle: 'Inner Chest & Squeeze',
            secondaryMuscles: 'Serratus Anterior',
            equipment: 'Dual Cable Pulley',
            sets: 3,
            reps: 15,
            weightKg: 12.5,
            restSeconds: 60,
            instructions: 'Slight bend in elbows. Bring handles together hugging an imaginary barrel. Hold peak contraction for 1 second.',
            photoUrl: '🏋️',
            previousPerformance: '3 sets × 15 reps @ 12.5kg',
          ),
          ExerciseDetail(
            id: 'mon_ex_4',
            name: 'Tricep Rope Pushdowns',
            targetMuscle: 'Lateral & Medial Triceps',
            secondaryMuscles: 'Forearms',
            equipment: 'Cable Pulley & Rope',
            sets: 4,
            reps: 12,
            weightKg: 17.5,
            restSeconds: 60,
            instructions: 'Lock elbows to the sides of your ribs. Spread the rope at the bottom of the movement for maximum contraction.',
            photoUrl: '💪',
            previousPerformance: '4 sets × 12 reps @ 17.5kg',
          ),
          ExerciseDetail(
            id: 'mon_ex_5',
            name: 'Overhead Dumbbell Extension',
            targetMuscle: 'Long Head Triceps',
            secondaryMuscles: 'Core Stabilizers',
            equipment: 'Single Heavy Dumbbell',
            sets: 3,
            reps: 12,
            weightKg: 15.0,
            restSeconds: 60,
            instructions: 'Press dumbbell overhead with both hands cup-gripping the top plate. Lower behind head until elbows hit 90 degrees.',
            photoUrl: '💪',
            previousPerformance: '3 sets × 12 reps @ 15kg',
          ),
        ],
      ),
      WorkoutDayPlan(
        id: 'plan_tuesday',
        dayName: 'Tuesday',
        workoutName: 'Back & Biceps Power',
        muscleGroup: 'Lats, Rhomboids, Biceps',
        estimatedDurationMinutes: 50,
        difficulty: 'Intermediate',
        status: WorkoutStatus.planned,
        exercises: [
          ExerciseDetail(
            id: 'tue_ex_1',
            name: 'Conventional Deadlift / Rack Pull',
            targetMuscle: 'Posterior Chain & Erector Spinae',
            secondaryMuscles: 'Glutes, Hamstrings, Traps, Forearms',
            equipment: 'Olympic Barbell & Bumper Plates',
            sets: 4,
            reps: 6,
            weightKg: 90.0,
            restSeconds: 120,
            instructions: 'Hinge at the hips with flat spine. Brace core with valsalva maneuver. Drive feet through floor and stand tall.',
            photoUrl: '🧗',
            previousPerformance: '4 sets × 6 reps @ 90kg',
          ),
          ExerciseDetail(
            id: 'tue_ex_2',
            name: 'Lat Pulldowns (Wide Grip)',
            targetMuscle: 'Latissimus Dorsi (V-Taper)',
            secondaryMuscles: 'Biceps, Rear Deltoids',
            equipment: 'Lat Pulldown Machine',
            sets: 4,
            reps: 10,
            weightKg: 45.0,
            restSeconds: 75,
            instructions: 'Slight backward lean. Pull bar towards upper chest by driving elbows down into back pockets.',
            photoUrl: '🧗',
            previousPerformance: '4 sets × 10 reps @ 45kg',
          ),
          ExerciseDetail(
            id: 'tue_ex_3',
            name: 'Seated Cable Row (Close V-Grip)',
            targetMuscle: 'Mid-Back, Rhomboids & Thickness',
            secondaryMuscles: 'Lower Lats, Biceps',
            equipment: 'Low Cable Row Machine',
            sets: 3,
            reps: 12,
            weightKg: 40.0,
            restSeconds: 60,
            instructions: 'Keep torso upright. Pull attachment to naval, squeezing shoulder blades tightly together.',
            photoUrl: '🧗',
            previousPerformance: '3 sets × 12 reps @ 40kg',
          ),
          ExerciseDetail(
            id: 'tue_ex_4',
            name: 'Standing Barbell Bicep Curls',
            targetMuscle: 'Biceps Brachii (Both Heads)',
            secondaryMuscles: 'Brachialis, Forearms',
            equipment: 'EZ-Bar or Straight Barbell',
            sets: 4,
            reps: 10,
            weightKg: 25.0,
            restSeconds: 60,
            instructions: 'Keep elbows tucked beside torso without swinging. Supinate wrists and curl up to shoulder level with 2s eccentric.',
            photoUrl: '💪',
            previousPerformance: '4 sets × 10 reps @ 25kg',
          ),
          ExerciseDetail(
            id: 'tue_ex_5',
            name: 'Incline Dumbbell Hammer Curls',
            targetMuscle: 'Brachioradialis & Arm Thickness',
            secondaryMuscles: 'Forearm Extensors',
            equipment: 'Dumbbells & 45° Incline Bench',
            sets: 3,
            reps: 12,
            weightKg: 12.0,
            restSeconds: 60,
            instructions: 'Maintain neutral palms-facing-in grip throughout. Deep stretch at bottom of incline.',
            photoUrl: '💪',
            previousPerformance: '3 sets × 12 reps @ 12kg',
          ),
        ],
      ),
      WorkoutDayPlan(
        id: 'plan_wednesday',
        dayName: 'Wednesday',
        workoutName: 'Quad & Hamstring Overload',
        muscleGroup: 'Quadriceps, Hamstrings, Glutes & Calves',
        estimatedDurationMinutes: 55,
        difficulty: 'Advanced',
        status: WorkoutStatus.planned,
        exercises: [
          ExerciseDetail(
            id: 'wed_ex_1',
            name: 'Barbell Back Squats',
            targetMuscle: 'Quadriceps & Gluteus Maximus',
            secondaryMuscles: 'Adductors, Core, Lower Back',
            equipment: 'Squat Rack & Barbell',
            sets: 4,
            reps: 8,
            weightKg: 75.0,
            restSeconds: 120,
            instructions: 'Rest bar across upper traps. Break at hips and knees simultaneously. Descend below parallel before driving up.',
            photoUrl: '🦵',
            previousPerformance: '4 sets × 8 reps @ 75kg',
          ),
          ExerciseDetail(
            id: 'wed_ex_2',
            name: 'Romanian Deadlifts (RDL)',
            targetMuscle: 'Hamstrings & Glute Ham Tie-in',
            secondaryMuscles: 'Lower Back, Erector Spinae',
            equipment: 'Barbell or Heavy Dumbbells',
            sets: 4,
            reps: 10,
            weightKg: 55.0,
            restSeconds: 90,
            instructions: 'Slight knee bend. Push hips back as far as possible until intense hamstring stretch is felt.',
            photoUrl: '🦵',
            previousPerformance: '4 sets × 10 reps @ 55kg',
          ),
          ExerciseDetail(
            id: 'wed_ex_3',
            name: 'Leg Press (45-Degree Incline)',
            targetMuscle: 'Quad Vastus Lateralis & Medialis',
            secondaryMuscles: 'Glutes',
            equipment: 'Leg Press Sled',
            sets: 3,
            reps: 12,
            weightKg: 140.0,
            restSeconds: 75,
            instructions: 'Position feet shoulder-width on carriage. Lower weight without rounding lower back off pad.',
            photoUrl: '🦵',
            previousPerformance: '3 sets × 12 reps @ 140kg',
          ),
          ExerciseDetail(
            id: 'wed_ex_4',
            name: 'Lying Leg Curls',
            targetMuscle: 'Hamstring Knee Flexion',
            secondaryMuscles: 'Gastrocnemius',
            equipment: 'Lying Leg Curl Machine',
            sets: 3,
            reps: 15,
            weightKg: 35.0,
            restSeconds: 60,
            instructions: 'Point toes toward shins to emphasize hamstrings. Pause at peak contraction.',
            photoUrl: '🦵',
            previousPerformance: '3 sets × 15 reps @ 35kg',
          ),
          ExerciseDetail(
            id: 'wed_ex_5',
            name: 'Standing Calf Raises',
            targetMuscle: 'Gastrocnemius & Soleus',
            secondaryMuscles: 'Achilles Tendon',
            equipment: 'Calf Block or Smith Machine',
            sets: 4,
            reps: 20,
            weightKg: 40.0,
            restSeconds: 45,
            instructions: 'Full 2-second stretch at bottom and 2-second peak squeeze at top.',
            photoUrl: '🦵',
            previousPerformance: '4 sets × 20 reps @ 40kg',
          ),
        ],
      ),
      WorkoutDayPlan(
        id: 'plan_thursday',
        dayName: 'Thursday',
        workoutName: 'Shoulders & Core Definition',
        muscleGroup: 'Deltoids, Traps, Abdominals & Obliques',
        estimatedDurationMinutes: 45,
        difficulty: 'Intermediate',
        status: WorkoutStatus.planned,
        exercises: [
          ExerciseDetail(
            id: 'thu_ex_1',
            name: 'Seated Overhead Dumbbell Press',
            targetMuscle: 'Anterior & Lateral Deltoids',
            secondaryMuscles: 'Upper Triceps, Core',
            equipment: 'Adjustable Bench (75°) & Dumbbells',
            sets: 4,
            reps: 8,
            weightKg: 18.0,
            restSeconds: 90,
            instructions: 'Press dumbbells up in a controlled arc without locking elbows at the top.',
            photoUrl: '💪',
            previousPerformance: '4 sets × 8 reps @ 18kg',
          ),
          ExerciseDetail(
            id: 'thu_ex_2',
            name: 'Dumbbell Lateral Raises',
            targetMuscle: 'Medial Lateral Deltoids (Boulder Shoulders)',
            secondaryMuscles: 'Upper Trapezius',
            equipment: 'Light-to-Moderate Dumbbells',
            sets: 4,
            reps: 15,
            weightKg: 8.0,
            restSeconds: 60,
            instructions: 'Slight forward lean. Lead with elbows up to shoulder level. Pour imaginary water pitchers.',
            photoUrl: '💪',
            previousPerformance: '4 sets × 15 reps @ 8kg',
          ),
          ExerciseDetail(
            id: 'thu_ex_3',
            name: 'Face Pulls with External Rotation',
            targetMuscle: 'Rear Delts, Rotator Cuff, Rhomboids',
            secondaryMuscles: 'Middle Traps',
            equipment: 'Cable Pulley & Rope Attachment',
            sets: 4,
            reps: 15,
            weightKg: 15.0,
            restSeconds: 60,
            instructions: 'Set pulley at forehead height. Pull rope towards eyes while spreading hands outwards.',
            photoUrl: '💪',
            previousPerformance: '4 sets × 15 reps @ 15kg',
          ),
          ExerciseDetail(
            id: 'thu_ex_4',
            name: 'Hanging Knee/Leg Raises',
            targetMuscle: 'Lower Rectus Abdominis',
            secondaryMuscles: 'Hip Flexors, Grip Strength',
            equipment: 'Pull-up Bar or Captains Chair',
            sets: 4,
            reps: 15,
            weightKg: 0.0,
            restSeconds: 60,
            instructions: 'Curl pelvis upwards towards chest rather than just swinging legs.',
            photoUrl: '🧘',
            previousPerformance: '4 sets × 15 reps (Bodyweight)',
          ),
        ],
      ),
      WorkoutDayPlan(
        id: 'plan_friday',
        dayName: 'Friday',
        workoutName: 'Upper Body Pump & Tonal Density',
        muscleGroup: 'Complete Upper Body Hypertrophy',
        estimatedDurationMinutes: 50,
        difficulty: 'Intermediate',
        status: WorkoutStatus.planned,
        exercises: [
          ExerciseDetail(
            id: 'fri_ex_1',
            name: 'Dumbbell Incline Bench Press',
            targetMuscle: 'Upper Chest & Front Deltoids',
            secondaryMuscles: 'Triceps',
            equipment: 'Dumbbells & Incline Bench',
            sets: 4,
            reps: 10,
            weightKg: 22.0,
            restSeconds: 75,
            instructions: 'Focus on maximum stretch and chest squeeze at peak lockout.',
            photoUrl: '🏋️',
            previousPerformance: '4 sets × 10 reps @ 22kg',
          ),
          ExerciseDetail(
            id: 'fri_ex_2',
            name: 'Chest-Supported T-Bar / Dumbbell Rows',
            targetMuscle: 'Mid-Back & Upper Lats',
            secondaryMuscles: 'Rear Delts, Biceps',
            equipment: 'Incline Bench & Pair of Dumbbells',
            sets: 4,
            reps: 10,
            weightKg: 20.0,
            restSeconds: 75,
            instructions: 'Lie prone on incline bench. Pull elbows high past torso.',
            photoUrl: '🧗',
            previousPerformance: '4 sets × 10 reps @ 20kg',
          ),
          ExerciseDetail(
            id: 'fri_ex_3',
            name: 'Cable Lateral Raises (Behind Back)',
            targetMuscle: 'Side Deltoid Isolation',
            secondaryMuscles: 'Traps',
            equipment: 'Low Single Cable Pulley',
            sets: 3,
            reps: 15,
            weightKg: 6.0,
            restSeconds: 45,
            instructions: 'Constant tension throughout entire range of motion.',
            photoUrl: '💪',
            previousPerformance: '3 sets × 15 reps @ 6kg',
          ),
          ExerciseDetail(
            id: 'fri_ex_4',
            name: 'Incline Dumbbell Curls',
            targetMuscle: 'Bicep Long Head Stretch',
            secondaryMuscles: 'Forearms',
            equipment: 'Incline Bench & Dumbbells',
            sets: 3,
            reps: 12,
            weightKg: 10.0,
            restSeconds: 60,
            instructions: 'Let arms hang vertically behind torso for maximum long-head stretch.',
            photoUrl: '💪',
            previousPerformance: '3 sets × 12 reps @ 10kg',
          ),
        ],
      ),
      WorkoutDayPlan(
        id: 'plan_saturday',
        dayName: 'Saturday',
        workoutName: 'Posterior Chain & Core Conditioning',
        muscleGroup: 'Hamstrings, Glutes, Calves & Deep Core',
        estimatedDurationMinutes: 45,
        difficulty: 'Intermediate',
        status: WorkoutStatus.planned,
        exercises: [
          ExerciseDetail(
            id: 'sat_ex_1',
            name: 'Barbell Hip Thrusts',
            targetMuscle: 'Gluteus Maximus & Upper Glute Shelf',
            secondaryMuscles: 'Hamstrings, Core',
            equipment: 'Barbell, Bench & Thick Foam Pad',
            sets: 4,
            reps: 10,
            weightKg: 80.0,
            restSeconds: 90,
            instructions: 'Drive through heels. Lock hips into full posterior pelvic tilt at the top.',
            photoUrl: '🦵',
            previousPerformance: '4 sets × 10 reps @ 80kg',
          ),
          ExerciseDetail(
            id: 'sat_ex_2',
            name: 'Walking Dumbbell Lunges',
            targetMuscle: 'Quads, Glutes & Dynamic Stability',
            secondaryMuscles: 'Hamstrings, Calves',
            equipment: 'Pair of Dumbbells',
            sets: 3,
            reps: 12,
            weightKg: 14.0,
            restSeconds: 75,
            instructions: 'Step forward landing smoothly. Lower back knee until 1 inch off floor.',
            photoUrl: '🦵',
            previousPerformance: '3 sets × 12 reps @ 14kg',
          ),
          ExerciseDetail(
            id: 'sat_ex_3',
            name: 'Seated Calf Raises',
            targetMuscle: 'Soleus Muscle',
            secondaryMuscles: 'Achilles Complex',
            equipment: 'Seated Calf Machine',
            sets: 4,
            reps: 15,
            weightKg: 35.0,
            restSeconds: 45,
            instructions: 'Slow controlled tempo with complete pause at the stretch.',
            photoUrl: '🦵',
            previousPerformance: '4 sets × 15 reps @ 35kg',
          ),
          ExerciseDetail(
            id: 'sat_ex_4',
            name: 'Cable Woodchoppers',
            targetMuscle: 'Obliques & Rotational Core',
            secondaryMuscles: 'Shoulders, Transverse Abdominis',
            equipment: 'Cable Pulley & Single D-Handle',
            sets: 3,
            reps: 15,
            weightKg: 12.0,
            restSeconds: 45,
            instructions: 'Rotate through torso keeping arms extended.',
            photoUrl: '🧘',
            previousPerformance: '3 sets × 15 reps @ 12kg',
          ),
        ],
      ),
      WorkoutDayPlan(
        id: 'plan_sunday',
        dayName: 'Sunday',
        workoutName: 'Active Recovery & Mobility Flow',
        muscleGroup: 'Full Body Mobility & CNS Recovery',
        estimatedDurationMinutes: 30,
        difficulty: 'Beginner',
        status: WorkoutStatus.restDay,
        exercises: [
          ExerciseDetail(
            id: 'sun_ex_1',
            name: 'Thoracic Spine Foam Rolling & Cat-Cow',
            targetMuscle: 'Thoracic Mobility & Spinal Flexion',
            secondaryMuscles: 'Lats, Rhomboids, Trapezius',
            equipment: 'Foam Roller & Yoga Mat',
            sets: 3,
            reps: 10,
            weightKg: 0.0,
            restSeconds: 30,
            instructions: 'Roll slowly along mid-back. Breathe deeply into extended spine positions.',
            photoUrl: '🧘',
            previousPerformance: 'Completed full 10-minute flow',
          ),
          ExerciseDetail(
            id: 'sun_ex_2',
            name: 'World’s Greatest Stretch',
            targetMuscle: 'Hip Flexors, Hamstrings, Adductors, T-Spine',
            secondaryMuscles: 'Ankles, Glutes',
            equipment: 'Yoga Mat',
            sets: 3,
            reps: 6,
            weightKg: 0.0,
            restSeconds: 30,
            instructions: 'Step into deep lunge. Place hands inside foot and rotate arm toward ceiling.',
            photoUrl: '🧘',
            previousPerformance: 'Completed 6 reps/side',
          ),
          ExerciseDetail(
            id: 'sun_ex_3',
            name: '90/90 Hip Mobility Flow',
            targetMuscle: 'Internal & External Hip Rotation',
            secondaryMuscles: 'Glute Medius, Piriformis',
            equipment: 'Yoga Mat',
            sets: 3,
            reps: 8,
            weightKg: 0.0,
            restSeconds: 30,
            instructions: 'Sit with both legs bent at 90 degrees. Transition smoothly without lifting hands.',
            photoUrl: '🧘',
            previousPerformance: 'Completed 8 reps/side',
          ),
        ],
      ),
    ];
  }
}
